---
- hosts: all
  sudo: yes
  tasks:
    - name: ensure packages required are installed
      yum: pkg={{ item }} state=latest
      with_items:
        - libaio
        - bc
        - flex
        - unzip
        - ruby
    - name: unzip oracle rpm
      command: /usr/bin/unzip -q /vagrant/oracle/oracle*.rpm.zip -d /vagrant/oracle creates=/vagrant/oracle/Disk1
    - name: install oracle
      shell: /bin/rpm -ivh /vagrant/oracle/Disk1/oracle-xe-11.2.0-1.0.x86_64.rpm creates=/u01
    - name: setup oracle config file from user config file
      template: src=../oracle/xe.j2 dest=/vagrant/oracle/xe.rsp
    - name: configure oracle
      shell: /etc/init.d/oracle-xe configure responseFile=/vagrant/oracle/xe.rsp
      ignore_errors: True
    - name: setup oracle environment
      shell: /bin/echo 'source /u01/app/oracle/product/11.2.0/xe/bin/oracle_env.sh' >> /home/vagrant/.bash_profile
    - name: stop ip tables
      shell: service iptables stop
    - name: set oracle listener
      shell: ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe /u01/app/oracle/product/11.2.0/xe/bin/sqlplus
        system/{{ oracle_password }}@localhost < /vagrant/oracle/set_listener.sql
    - name: setup tablespaces/do some initialization
      shell: ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe /u01/app/oracle/product/11.2.0/xe/bin/sqlplus
        system/{{ oracle_password }}@localhost < /vagrant/oracle/init.sql
    - name: create databases from the .dmp files in /oracle/
      shell: ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe /u01/app/oracle/product/11.2.0/xe/bin/sqlplus
        system/{{ oracle_password }}@localhost @/vagrant/oracle/create_db.sql {{ item }} {{ oracle_password }}
      with_items: databases
    - name: create test databases from the .dmp files in /oracle/
      shell: ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe /u01/app/oracle/product/11.2.0/xe/bin/sqlplus
        system/{{ oracle_password }}@localhost @/vagrant/oracle/create_db.sql "{{ item }}_test" {{ oracle_password }}
      with_items: databases
      when: create_test_databases == true
    - name: adding stragg and encrypt_password functions
      shell: ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe /u01/app/oracle/product/11.2.0/xe/bin/sqlplus
        system/{{ oracle_password }}@localhost < /vagrant/oracle/extra_functions.sql
    - name: put the oracle user in the vagrant group
      user: name=oracle groups=vagrant
    - name: actually import databases from the .dmp files
      shell: /vagrant/oracle/impdp.sh {{ item }} {{ oracle_password }}
        creates=/vagrant/oracle/dump/{{ item }}_imp.log
      with_items: databases
      ignore_errors: True
    - name: creating test database schemas
      shell: /vagrant/oracle/impdp_test.sh {{ item }} {{ oracle_password }}
        creates=/vagrant/oracle/dump/{{ item }}_test_imp.log
      with_items: databases
      ignore_errors: True
      when: create_test_databases == true
    - name: add any extra oracle files
      shell: ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe /u01/app/oracle/product/11.2.0/xe/bin/sqlplus
        {{ item.db }}/{{ oracle_password }}@localhost < /vagrant/oracle/custom_sql/{{ item.db }}/{{ item.file }}.sql
      with_items: extra_sql
